By using tensorflow

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
import pandas as pd
df=pd.read_csv('/content/insurance_data.csv')
df

age  affordability  have_insurance
0    22              1               0
1    25              0               0
2    47              1               1
3    52              0               0
4    46              1               1
5    56              1               1
6    55              0               0
7    60              0               1
8    62              1               1
9    61              1               1
10   18              1               0
11   28              1               0
12   27              0               1
13   30              1               1
14   35              0               0
15   40              1               1
16   45              0               1
17   50              1               1
18   65              0               0
19   70              1               1

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df[['age', 'affordability']],df.have_insurance,test_size=0.2,random_state=25)

In [ ]:
x_train

age  affordability
6    55              0
18   65              0
16   45              0
0    22              1
3    52              0
7    60              0
1    25              0
5    56              1
14   35              0
9    61              1
19   70              1
17   50              1
8    62              1
12   27              0
15   40              1
4    46              1

In [ ]:
len(x_train)

16

In [ ]:
df.shape

(20, 3)

converting age as decimals so it matches affordability so that age and affordabiity raises between 0 and 1

In [ ]:
# Scale the 'age' feature by dividing by 100
x_train_scaled = x_train.copy()
x_train_scaled['age'] = x_train_scaled['age'] / 100

x_test_scaled = x_test.copy()
x_test_scaled['age'] = x_test_scaled['age'] / 100

# Display the scaled training set
x_train_scaled


age  affordability
6   0.55              0
18  0.65              0
16  0.45              0
0   0.22              1
3   0.52              0
7   0.60              0
1   0.25              0
5   0.56              1
14  0.35              0
9   0.61              1
19  0.70              1
17  0.50              1
8   0.62              1
12  0.27              0
15  0.40              1
4   0.46              1

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid',
                       kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(x_train_scaled,y_train,epochs=500)

Epoch 1/500


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 580ms/step - accuracy: 0.6250 - loss: 0.5688
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6250 - loss: 0.5686
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6250 - loss: 0.5685
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.6250 - loss: 0.5683
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6250 - loss: 0.5682
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6250 - loss: 0.5680
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6250 - loss: 0.5679
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6250 - loss: 0.5677
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6250 - loss: 0.5676
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6250 - loss: 0.5675
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6250 - loss: 0.5673
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6250 - loss: 0.5672


In [ ]:
model.evaluate(x_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 0.5000 - loss: 0.8789


[0.8788726925849915, 0.5]

In [ ]:
model.predict(x_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step


array([[0.7942762],
       [0.7918154],
       [0.8143224],
       [0.7791867]], dtype=float32)

In [ ]:
y_test

13    1
11    0
2     1
10    0
Name: have_insurance, dtype: int64

In [ ]:
coef,intercept=model.get_weights()
coef,intercept

(array([[0.7496939],
        [1.5041077]], dtype=float32),
 array([-0.37811917], dtype=float32))

without using tensorflow

In [ ]:
def sigmoid(x):
    import math
    return 1 / (1 + math.exp(-x))

sigmoid(18)


0.9999999847700205

In [ ]:
def prediction_function(age, affordability):
    weighted_sum = coef[0] * age + coef[1] * affordability + intercept
    return sigmoid(weighted_sum)


In [ ]:
prediction_function(0.47, 1)



/tmp/ipython-input-1887710841.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.8143224240280531

In [ ]:

prediction_function(0.18, 1)


/tmp/ipython-input-1887710841.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.779186745405666

In [ ]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i, epsilon) for i in y_predicted]
    y_predicted_new = [min(i, 1 - epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true * np.log(y_predicted_new) +
                    (1 - y_true) * np.log(1 - y_predicted_new))


In [ ]:
def sigmoid_numpy(X):
    return 1 / (1 + np.exp(-X))

sigmoid_numpy(np.array([12, 0, 1]))


array([0.99999386, 0.5       , 0.73105858])

In [ ]:
def gradient_descent(age, affordability, y_true, epochs):
    # w1, w2, bias
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)

    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)

        loss = log_loss(y_true, y_predicted)

        w1d = (1 / n) * np.dot(np.transpose(age), (y_predicted - y_true))
        w2d = (1 / n) * np.dot(np.transpose(affordability), (y_predicted - y_true))
        bias_d = np.mean(y_predicted - y_true)

        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print(f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

    return w1, w2


In [ ]:
gradient_descent(x_train_scaled['age'],
                 x_train_scaled['affordability'],
                 y_train,
                 1000)


Epoch:0, w1:0.9860465331693796, w2:1.014267212715732, bias:-0.04481017306367721, loss:0.5687548076355038
Epoch:1, w1:0.9741888851466628, w2:1.0299414992430105, bias:-0.08517538483553624, loss:0.5641502500853277
Epoch:2, w1:0.9641765053969256, w2:1.0467888306921604, bias:-0.12162330861868978, loss:0.5602802910890038
Epoch:3, w1:0.9557809256956163, w2:1.0645950206635726, bias:-0.1546339646737021, loss:0.5569803636274642
Epoch:4, w1:0.9487967207648259, w2:1.083167441187271, bias:-0.18463816977070635, loss:0.554123208045328
Epoch:5, w1:0.9430412413492669, w2:1.102335335889124, bias:-0.21201844946614054, loss:0.55161146268671
Epoch:6, w1:0.9383535323301588, w2:1.1219491559860697, bias:-0.23711156292063018, loss:0.5493712185339275
Epoch:7, w1:0.9345927592535396, w2:1.141879268348309, bias:-0.26021198032540716, loss:0.5473466574726855
Epoch:8, w1:0.93163638286494, w2:1.1620143045721294, bias:-0.28157582826417704, loss:0.545495734849004
Epoch:9, w1:0.9293782502845415, w2:1.1822593473266447, bi

(np.float64(3.510245172984123), np.float64(2.381090512578096))

In [ ]:
coef,intercept

(array([[0.7496939],
        [1.5041077]], dtype=float32),
 array([-0.37811917], dtype=float32))

here data set is not proper that's why we didn't get similar values for coef ,intercept and also w1,w2,bias..if model predicts well coef,intercept similar to w1,w2,bias